package ma.srmanager.coreapi.enums.soustraitance;

public enum TimeLineCreateStLevel {
    SOUS_TRAITANCE_IN_CREATION,
    ARTICLE_IN_BORDEREAU_SELECTED,
    ARTICLE_OUT_BORDEREAU_SELECTED,
    SOUS_TRAITANT_SELECTED,
    DEVIS_CREATED,
    MOINS_DISANT_SELECTED,
    DATA_CONTRACTOR_VALIDATED,
    CONTRACT_CREATED,
    FILES_CONTRACTOR_UPDATED,
    SOUS_TRAITANCE_CREATED
}
