package ma.srmanager.coreapi.enums.caisse;

public enum IntituleCaisse {
    CAISSE_CENTRALE,
    CAISSE_ADMINISTRATION,
    CAISSE_DIRECTION_GENERALE,
    CAISSE_DIRECTION_EXPLOITATION,
    CAISSE_DIRECTION_TECHNIQUE,
    CAISSE_CHANTIER,
    CAISSE_SI,
}
